# Generated by Django 6.0.2 on 2026-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Quick Link',
                'verbose_name_plural': 'Footer Quick Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterServiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Service Link',
                'verbose_name_plural': 'Footer Service Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(help_text='e.g. /services/ or #services for an anchor link.', max_length=200)),
                ('icon_class', models.CharField(default='ti ti-info-circle', help_text="Tabler icon class shown on hover, e.g. 'ti ti-flask'.", max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Vetri IT Systems Pvt Ltd', help_text='Shown in the header next to the logo, and in the browser tab.', max_length=100)),
                ('logo', models.ImageField(help_text='Header + footer logo. Transparent PNG recommended.', upload_to='site/')),
                ('tagline', models.CharField(blank=True, default='We provide website, app, and software solutions to help businesses grow digitally.', help_text='Short line shown under the logo in the footer.', max_length=200)),
                ('phone', models.CharField(blank=True, default='+91-1234567890', max_length=30)),
                ('email', models.EmailField(blank=True, default='businessteam@vetriitsystems.com', max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('get_in_touch_text', models.CharField(default='Get in Touch', max_length=40)),
                ('get_in_touch_url', models.CharField(default='/contact/', max_length=200)),
                ('footer_connect_heading', models.CharField(default="Let's Connect there", max_length=100)),
                ('copyright_text', models.CharField(default='© 2026 Vetri IT Systems. All Rights Reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
