# Generated by Django 6.0.2 on 2026-07-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_button_text',
            field=models.CharField(default='Contact Now', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_button_url',
            field=models.CharField(default='/contact/', max_length=200),
        ),
    ]
