# Generated by Django 6.0.2 on 2026-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_contact_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('our_products', 'Our Products'), ('solutions', 'Solutions'), ('careers', 'Careers'), ('contact', 'Contact')], help_text='Which page this banner appears on. Only one banner per page.', max_length=20, unique=True)),
                ('heading', models.CharField(help_text="Full heading text, e.g. 'Empowering Businesses with Smart Digital Solutions'.", max_length=200)),
                ('highlight_text', models.CharField(blank=True, help_text="Exact word/phrase inside the heading to color purple, e.g. 'Solutions'. Leave blank for no highlight.", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Illustration/graphic shown on the right side of the banner.', null=True, upload_to='banners/')),
                ('cta_1_text', models.CharField(blank=True, default='Explore Services', max_length=40)),
                ('cta_1_url', models.CharField(blank=True, default='/services/', max_length=200)),
                ('cta_2_text', models.CharField(blank=True, default='Contact Us', max_length=40)),
                ('cta_2_url', models.CharField(blank=True, default='/contact/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
    ]
