# Generated by Django 6.0.2 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Checklist Item',
                'verbose_name_plural': 'About — Checklist Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutHighlightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/highlight_cards/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Highlight Card',
                'verbose_name_plural': 'About — Highlight Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='About Vetri IT Systems', max_length=100)),
                ('heading', models.CharField(default='Your Strategic Partner in Digital Excellence', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quote_text', models.CharField(blank=True, help_text='Shown in the quote card between the highlight cards and the intro text.', max_length=300)),
            ],
            options={
                'verbose_name': 'About — Intro Section',
                'verbose_name_plural': 'About — Intro Section',
            },
        ),
        migrations.CreateModel(
            name='AboutMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/mission_vision/')),
                ('title', models.CharField(help_text="e.g. 'Our Mission' or 'Our Vision'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Mission / Vision Card',
                'verbose_name_plural': 'About — Mission / Vision Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/service_cards/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Core Service Card',
                'verbose_name_plural': 'About — Core Service Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="e.g. '5+', '500+', '100%', '24/7'", max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Stat',
                'verbose_name_plural': 'About — Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutValueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='How We Deliver Value', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/value_section/')),
            ],
            options={
                'verbose_name': 'About — Value Section',
                'verbose_name_plural': 'About — Value Section',
            },
        ),
        migrations.CreateModel(
            name='AboutValueStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='The number shown in the circle, e.g. 1, 2, 3, 4.')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Value Step',
                'verbose_name_plural': 'About — Value Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutWhyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/why_cards/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About — Why Card',
                'verbose_name_plural': 'About — Why Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutWhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Why Work With Us', max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'About — Why Section',
                'verbose_name_plural': 'About — Why Section',
            },
        ),
    ]
