# Generated by Django 6.0.2 on 2026-07-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutchecklistitem_abouthighlightcard_aboutintro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/industries/')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services — Industry Card',
                'verbose_name_plural': 'Services — Industry Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Main illustration shown by default (e.g. the 'WEBSITE DEVELOPMENT' graphic).", upload_to='services/cards/')),
                ('icon', models.ImageField(blank=True, help_text='Small icon shown in the hover state (e.g. the orange phone icon).', null=True, upload_to='services/card_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('cta_text', models.CharField(default='Explore Service', max_length=40)),
                ('cta_url', models.CharField(blank=True, default='#', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services — Service Card',
                'verbose_name_plural': 'Services — Service Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkingProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/process_steps/')),
                ('title', models.CharField(help_text="e.g. 'Requirement Analysis'", max_length=100)),
                ('step_number', models.PositiveIntegerField(help_text='Determines the sequence order of the reveal animation.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services — Working Process Step',
                'verbose_name_plural': 'Services — Working Process Steps',
                'ordering': ['order'],
            },
        ),
    ]
