# Generated by Django 6.0.2 on 2026-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_industrycard_servicecard_workingprocessstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='products/icons/')),
                ('title', models.CharField(help_text="e.g. 'VTMS - Vetri Training Management System'", max_length=150)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(help_text='Dashboard/product screenshot shown beside or below the text.', upload_to='products/screenshots/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Card with the lowest order number renders full-width as the featured product.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Products — Product Card',
                'verbose_name_plural': 'Products — Product Cards',
                'ordering': ['order'],
            },
        ),
    ]
