# Generated by Django 6.0.2 on 2026-07-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='url',
            field=models.CharField(default='#', help_text='Where clicking the card leads — internal page or external product link.', max_length=200),
        ),
    ]
