# Generated by Django 6.0.2 on 2026-07-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productcard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='productcard',
            name='tagline',
            field=models.CharField(blank=True, help_text="Short subheading shown on the product detail page, e.g. 'Simplify Billing, Manage Sales, and Grow Your Business'.", max_length=200),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.productcard')),
            ],
            options={
                'verbose_name': 'Products — Gallery Image',
                'verbose_name_plural': 'Products — Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
