# Generated by Django 6.0.2 on 2026-07-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productcard_slug_productcard_tagline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
