# Generated by Django 6.0.2 on 2026-07-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_productcard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='solutions/cards/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Solutions — Solution Card',
                'verbose_name_plural': 'Solutions — Solution Cards',
                'ordering': ['order'],
            },
        ),
    ]
