# Generated by Django 6.0.2 on 2026-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solutioncard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='careers/benefit_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Careers — Benefit Card',
                'verbose_name_plural': 'Careers — Benefit Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BenefitsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Benefits', max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Careers — Benefits Heading',
                'verbose_name_plural': 'Careers — Benefits Heading',
            },
        ),
        migrations.CreateModel(
            name='CareerHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Join the Future of Digital Innovation', max_length=200)),
                ('highlight_text', models.CharField(default='Future', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='View Open Roles', max_length=40)),
                ('cta_anchor', models.CharField(default='#open-positions', help_text="Anchor link on this same page, e.g. '#open-positions'.", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/hero/')),
            ],
            options={
                'verbose_name': 'Careers — Hero Section',
                'verbose_name_plural': 'Careers — Hero Section',
            },
        ),
        migrations.CreateModel(
            name='CultureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='careers/culture_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Careers — Culture Card',
                'verbose_name_plural': 'Careers — Culture Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CultureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Culture', max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Careers — Culture Heading',
                'verbose_name_plural': 'Careers — Culture Heading',
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='careers/job_icons/')),
                ('title', models.CharField(help_text="e.g. 'Senior Product Designer'", max_length=150)),
                ('apply_url', models.URLField(default='https://vetrijobs.com')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Careers — Job Opening',
                'verbose_name_plural': 'Careers — Job Openings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LifeAtVISImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='careers/life_at_vis/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Careers — Life at VIS Image',
                'verbose_name_plural': 'Careers — Life at VIS Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LifeAtVISSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Life at VIS', max_length=150)),
                ('subheading', models.CharField(default='A glimpse into our world, our people.', max_length=200)),
            ],
            options={
                'verbose_name': 'Careers — Life at VIS Heading',
                'verbose_name_plural': 'Careers — Life at VIS Heading',
            },
        ),
        migrations.CreateModel(
            name='OpenPositionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Career Opportunities', max_length=100)),
                ('heading', models.CharField(default='Open Positions', max_length=150)),
            ],
            options={
                'verbose_name': 'Careers — Open Positions Heading',
                'verbose_name_plural': 'Careers — Open Positions Heading',
            },
        ),
    ]
