# Generated by Django 6.0.2 on 2026-07-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_benefitcard_benefitssection_careerhero_culturecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSomethingCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default="Let's Build Something Amazing Together", max_length=200)),
                ('description', models.TextField(blank=True, default='Ready to take your digital presence to the next level? Our team is standing by to help you scale.')),
                ('primary_button_text', models.CharField(default='Start Your Project', max_length=40)),
                ('secondary_button_text', models.CharField(default='Enquiry', max_length=40)),
                ('button_url', models.CharField(default='/contact/', help_text='Both buttons link here.', max_length=200)),
            ],
            options={
                'verbose_name': 'Build Something CTA (shared)',
                'verbose_name_plural': 'Build Something CTA (shared)',
            },
        ),
    ]
