# Generated by Django 6.0.2 on 2026-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_buildsomethingcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text="e.g. 'Surandai - Shanthi Complex - Branch 1'", max_length=150)),
                ('address', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact — Location',
                'verbose_name_plural': 'Contact — Locations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_us_number', models.CharField(default='+91-1234567890', max_length=30)),
                ('company_email', models.EmailField(help_text="Where 'Send Message' form submissions are delivered.", max_length=254)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps: Share > Embed a map > copy the src URL from the iframe code.')),
            ],
            options={
                'verbose_name': 'Contact — Page Info',
                'verbose_name_plural': 'Contact — Page Info',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact — Form Submission',
                'verbose_name_plural': 'Contact — Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact — FAQ',
                'verbose_name_plural': 'Contact — FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, help_text="Full heading text, e.g. 'Empowering Businesses with Smart Digital Solutions'.", max_length=200),
        ),
    ]
