# Generated by Django 6.0.2 on 2026-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactlocation_contactpageinfo_contactsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpageinfo',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps: Share > Embed a map > copy the src URL from the iframe code.', max_length=500),
        ),
    ]
