# Generated by Django 6.0.2 on 2026-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contactpageinfo_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We Build Websites, Apps &Software That Grow Your Business', max_length=200)),
                ('highlight_text', models.CharField(default='Grow Your Business', help_text='Portion of the heading colored purple.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cta_1_text', models.CharField(default='Get Start', max_length=40)),
                ('cta_1_url', models.CharField(default='#', max_length=200)),
                ('cta_2_text', models.CharField(default='View Our Services', max_length=40)),
                ('cta_2_url', models.CharField(default='/services/', max_length=200)),
                ('background_image', models.ImageField(blank=True, help_text='Abstract gradient/shapes background layer, sits behind both characters.', null=True, upload_to='home/hero/')),
                ('sitting_man_image', models.ImageField(blank=True, help_text='Static character, no animation.', null=True, upload_to='home/hero/')),
                ('standing_man_image', models.ImageField(blank=True, help_text='Character that continuously floats up and down.', null=True, upload_to='home/hero/')),
            ],
            options={
                'verbose_name': 'Home — Hero Section',
                'verbose_name_plural': 'Home — Hero Section',
            },
        ),
    ]
