# Generated by Django 6.0.2 on 2026-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_homehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home — About Checklist Item',
                'verbose_name_plural': 'Home — About Checklist Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Vetri IT System', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/about/')),
                ('cta_text', models.CharField(default='Learn More', max_length=40)),
                ('cta_url', models.CharField(default='/about/', max_length=200)),
            ],
            options={
                'verbose_name': 'Home — About Section',
                'verbose_name_plural': 'Home — About Section',
            },
        ),
    ]
