# Generated by Django 6.0.2 on 2026-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homeaboutchecklistitem_homeaboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Working Process', max_length=150)),
                ('background_image', models.ImageField(blank=True, help_text='The full curved-path artwork with numbered circles, blobs, dot grid — exported as one image from Figma.', null=True, upload_to='home/process/')),
            ],
            options={
                'verbose_name': 'Home — Process Section',
                'verbose_name_plural': 'Home — Process Section',
            },
        ),
        migrations.CreateModel(
            name='HomeProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('position_x', models.FloatField(help_text="Horizontal position of this step's circle, as a % (0-100) of the image width.")),
                ('position_y', models.FloatField(help_text="Vertical position of this step's circle, as a % (0-100) of the image height.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home — Process Step',
                'verbose_name_plural': 'Home — Process Steps',
                'ordering': ['order'],
            },
        ),
    ]
