# Generated by Django 6.0.2 on 2026-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homeprocesssection_homeprocessstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProcessFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/process_frames/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home — Process Frame',
                'verbose_name_plural': 'Home — Process Frames',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='HomeProcessStep',
        ),
        migrations.RemoveField(
            model_name='homeprocesssection',
            name='background_image',
        ),
    ]
