# Generated by Django 6.0.2 on 2026-07-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_homeprocessframe_delete_homeprocessstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/service_cards/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home — Exclusive Service Card',
                'verbose_name_plural': 'Home — Exclusive Service Cards',
                'ordering': ['order'],
            },
        ),
    ]
