# Generated by Django 6.0.2 on 2026-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homeservicecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWhyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home/why_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home — Why Card',
                'verbose_name_plural': 'Home — Why Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeWhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Why Work With Us', max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Home — Why Section',
                'verbose_name_plural': 'Home — Why Section',
            },
        ),
    ]
