# Generated by Django 6.0.2 on 2026-07-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_homewhycard_homewhysection'),
    ]

    operations = [

        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/features/')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.servicecard')),
            ],
            options={
                'verbose_name': 'Services — Feature',
                'verbose_name_plural': 'Services — Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSolutionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_image', models.ImageField(upload_to='services/solution_cards/default/')),
                ('hover_image', models.ImageField(upload_to='services/solution_cards/hover/')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_cards', to='core.servicecard')),
            ],
            options={
                'verbose_name': 'Services — Solution Card',
                'verbose_name_plural': 'Services — Solution Cards',
                'ordering': ['order'],
            },
        ),
    ]