# Generated by Django 6.0.2 on 2026-07-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_servicecard_cta_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesolutioncard',
            name='hover_image',
        ),
    ]
