# Generated by Django 6.0.2 on 2026-07-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_servicesolutioncard_hover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesolutioncard',
            name='hover_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicesolutioncard',
            name='hover_icon',
            field=models.ImageField(blank=True, help_text='Small icon shown inside the orange rotating square on hover.', null=True, upload_to='services/solution_cards/hover_icons/'),
        ),
        migrations.AddField(
            model_name='servicesolutioncard',
            name='price_text',
            field=models.CharField(blank=True, help_text="e.g. '10,000' — shown in the 'Starting From' flag.", max_length=40),
        ),
        migrations.CreateModel(
            name='ServiceSolutionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('solution_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.servicesolutioncard')),
            ],
            options={
                'verbose_name': 'Services — Solution Checklist Item',
                'verbose_name_plural': 'Services — Solution Checklist Items',
                'ordering': ['order'],
            },
        ),
    ]
