# Generated by Django 6.0.2 on 2026-07-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_servicesolutioncard_hover_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='brochure_file',
            field=models.FileField(blank=True, help_text="PDF brochure for this product. If left empty, the 'Download Brochure' button is hidden.", null=True, upload_to='products/brochures/'),
        ),
    ]