# Generated by Django 6.0.2 on 2026-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_servicecard_cta_url_productcard_brochure_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecard',
            name='cta_url',
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_cta1_text',
            field=models.CharField(default='Get Start', max_length=40),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_cta1_url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_cta2_text',
            field=models.CharField(default='Contact Us', max_length=40),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_cta2_url',
            field=models.CharField(default='/contact/', max_length=200),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_heading',
            field=models.CharField(blank=True, help_text="e.g. 'Website Services'", max_length=150),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/detail_banners/'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_explanation_heading',
            field=models.CharField(blank=True, help_text="e.g. 'Professional Website Development Services'", max_length=200),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='detail_explanation_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='features_heading',
            field=models.CharField(blank=True, default='What You Get', max_length=150),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='solutions_heading',
            field=models.CharField(blank=True, default='Our Website Solutions', max_length=150),
        ),
    ]
